### ISSUE TITLE
Merging anchors

### ISSUE THREAD

**Issue by simlu** [fregante/regex-join#1]
I found your package after having a similar requirement. However it doesn't seem to deal nicely with anchors. I've implemented and released my own and maybe you can take inspiration from it

https://github.com/blackflux/regex-merge

Take a look at the tests in particular

**Comment by fregante** [comment]
Thanks for opening an issue. I'd rather not do that because that `regex-merge` completely discards part of the regex.

```js
merge(/^a$/, /^b$/, /^c$/);
// => /^abc$/
```

Anchors are part of the regex itself so discarding them changes the meaning of the regex.

---

In `regex-join`, each part still works on its own and matches the final expected string string:

```js
const string = 'hello';
regexJoin(/^he/, 'll', /o$/).test(string) // -> true

// But also each part separately:

/^he/.test(string) // -> true
string.includes('ll') // -> true
/o$/.test(string) // -> true
```

but that's not possible with `regex-merge`:


```js
const string = 'abc';
merge(/^a$/, /^b$/, /^c$/).test(string) // -> true

// Not each part separately:

/^a$/.test(string) // -> false
/^b$/.test(string) // -> false
/^c$/.test(string) // -> false
```
